name: mondo_pelosetti
description: "Mondo Pelosetti - App per segnalare animali smarriti e feriti."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.0
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  geolocator: any
  permission_handler: any
  intl: any
  cached_network_image: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/